name: Java CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify code is formatted
        run: ./mvnw git-code-format:validate-code-format
      - name: Build jar
        run: ./mvnw package -DskipTests
      - name: Run all test
        run: ./mvnw test jacoco:report
      - name: Execute scenarios
        run: ./run-tests
